sonar.projectKey=oblivion-hq_inkwell
sonar.organization=oblivion-hq
sonar.sources=blog,user,blog_project
sonar.tests=blog/tests.py,user/tests.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true